packages:
  - studio
  - frontend

onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
  - sharp
  - unrs-resolver

minimumReleaseAge: 1440

allowBuilds:
  '@google/genai': true
  esbuild: true
  protobufjs: true
  sharp: true
  unrs-resolver: true

minimumReleaseAgeExclude:
  - '@sanity/access-ui@6.10.1'
  - '@sanity/diff@6.10.1'
  - '@sanity/mutator@6.10.1'
  - '@sanity/schema@6.10.1'
  - '@sanity/types@6.10.1'
  - '@sanity/util@6.10.1'
  - '@sanity/vision@6.10.1'
  - sanity@6.10.1
