packages:
  - studio
  - frontend

onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
  - sharp
  - unrs-resolver

minimumReleaseAge: 10080

allowBuilds:
  '@google/genai': true
  esbuild: true
  protobufjs: true
  sharp: true
  unrs-resolver: true
